name: release

on:
  push:
    tags:
      - "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Install Ubuntu dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y libdbus-1-dev pkg-config

      - name: "Create env file"
        run: |
          touch .env
          echo LASTFM_API_KEY=${{ secrets.LASTFM_API_KEY }} >> .env

      - name: Build
        run: |
          cargo build --release

      - name: Create .deb package
        run: |
          cargo install cargo-deb
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y dpkg dpkg-dev liblzma-dev
          cargo deb --output target/release/mpris-discord-rpc.deb

      - name: Create .rpm package
        run: |
          cargo install cargo-generate-rpm
          cargo generate-rpm -o target/release/mpris-discord-rpc.rpm

      - name: GH Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: .github/release-notes.md
          files: |
            target/release/mpris-discord-rpc
            target/release/mpris-discord-rpc.deb
            target/release/mpris-discord-rpc.rpm
